import { defineConfig } from 'vitest/config';
import path from 'path';

export default defineConfig({
  test: {
    globals: true,
    environment: 'jsdom',
    pool: 'forks',
    setupFiles: ['./src/test/setup.ts'],
    include: ['src/**/*.{test,spec}.{ts,tsx}', 'tests/**/*.{test,spec}.{ts,tsx}'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html', 'lcov'],
      reportsDirectory: './coverage',
      thresholds: {
        statements: 80,
        branches: 75,
        functions: 80,
        lines: 80,
      },
      include: [
        'src/styles/tokens.ts',
        'src/types/**/*.ts',
        'src/contexts/**/*.tsx',
        'src/components/ThemeToggle.tsx',
        'src/components/AppHeader.tsx',
        'src/components/PrivacyBadge.tsx',
        'src/components/StatusIndicators.tsx',
        'src/components/ScannerLayout/ScannerLayout.tsx',
        'src/components/StatusBar.tsx',
        'src/components/PasteInputPanel.tsx',
        'src/components/ScanButton.tsx',
        'src/components/About/**/*.tsx',
        'src/hooks/useModelStatus.ts',
        'src/hooks/useScanEngine.ts',
        'src/infra/input-sanitizer.ts',
        'src/orchestration/text-preprocessor.ts',
        'src/orchestration/findings-aggregator.ts',
        'src/orchestration/confidence-scorer.ts',
        'src/orchestration/scan-orchestrator.ts',
        'src/engines/regex/pattern-registry.ts',
        'src/engines/regex/regex-engine.ts',
        'src/engines/entropy/calculate-entropy.ts',
        'src/engines/entropy/word-list.ts',
        'src/engines/entropy/dictionary-filter.ts',
        'src/engines/entropy/contextual-signals.ts',
        'src/engines/entropy/entropy-analyzer.ts',
        'src/config/csp.ts',
        'scripts/verify-lockfile-integrity.ts',
        'src/test/helpers/**/*.ts',
      ],
      exclude: [
        'node_modules/',
        'dist/',
        'coverage/',
        'src/test/setup.ts',
        'src/types/index.ts',
        'src/contexts/index.ts',
        'src/infra/index.ts',
        'src/orchestration/index.ts',
        'src/engines/index.ts',
        '**/*.d.ts',
        '**/*.test.ts',
        '**/*.test.tsx',
      ],
    },
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
});
