/**
 * Canonical error codes for AirGap Scanner (WO-047).
 * Includes architecture-required codes plus aliases used by the scan/worker pipeline.
 */
export enum ErrorCode {
  WEBGPU_UNAVAILABLE = 'WEBGPU_UNAVAILABLE',
  WEBGPU_ADAPTER_FAILURE = 'WEBGPU_ADAPTER_FAILURE',
  MODEL_DOWNLOAD_FAILED = 'MODEL_DOWNLOAD_FAILED',
  MODEL_HASH_MISMATCH = 'MODEL_HASH_MISMATCH',
  MODEL_CACHE_CORRUPT = 'MODEL_CACHE_CORRUPT',
  LLM_WORKER_CRASH = 'LLM_WORKER_CRASH',
  LLM_INFERENCE_TIMEOUT = 'LLM_INFERENCE_TIMEOUT',
  REGEX_ENGINE_ERROR = 'REGEX_ENGINE_ERROR',
  ENTROPY_ENGINE_ERROR = 'ENTROPY_ENGINE_ERROR',
  SCAN_ABORTED = 'SCAN_ABORTED',
  INPUT_TOO_LARGE = 'INPUT_TOO_LARGE',
  MEMORY_PRESSURE = 'MEMORY_PRESSURE',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  // Pipeline aliases (kept for existing orchestration / worker callers)
  MODEL_LOAD_FAILED = 'MODEL_LOAD_FAILED',
  MODEL_VERIFICATION_FAILED = 'MODEL_VERIFICATION_FAILED',
  WEBGPU_INIT_FAILED = 'WEBGPU_INIT_FAILED',
  WORKER_INITIALIZATION_FAILED = 'WORKER_INITIALIZATION_FAILED',
  ANALYSIS_TIMEOUT = 'ANALYSIS_TIMEOUT',
  INFERENCE_FAILED = 'INFERENCE_FAILED',
  INFERENCE_TIMEOUT = 'INFERENCE_TIMEOUT',
  DETECTION_LAYER_FAILED = 'DETECTION_LAYER_FAILED',
  SCAN_ENGINE_FAILED = 'SCAN_ENGINE_FAILED',
}

/** Minimum codes required by WO-047 acceptance criteria. */
export const REQUIRED_ERROR_CODES = [
  ErrorCode.WEBGPU_UNAVAILABLE,
  ErrorCode.WEBGPU_ADAPTER_FAILURE,
  ErrorCode.MODEL_DOWNLOAD_FAILED,
  ErrorCode.MODEL_HASH_MISMATCH,
  ErrorCode.MODEL_CACHE_CORRUPT,
  ErrorCode.LLM_WORKER_CRASH,
  ErrorCode.LLM_INFERENCE_TIMEOUT,
  ErrorCode.REGEX_ENGINE_ERROR,
  ErrorCode.ENTROPY_ENGINE_ERROR,
  ErrorCode.SCAN_ABORTED,
  ErrorCode.INPUT_TOO_LARGE,
  ErrorCode.MEMORY_PRESSURE,
  ErrorCode.UNKNOWN_ERROR,
] as const;
